language: python
sudo: false
python:
- 3.5
- 3.4
- 3.3
- 3.2
- 3.1
- 3.0
- 2.7
- 2.6
env:
  global:
    secure: as/YLpq4Pkw0oCsouV/jO+wYjaXSTV07gQYXCSC4F8F4i7Ops7qnoemn6ch/hG+nlRsw3O1sjz9M0w7mty7fhzGUdWGqFMUrjbJv9g/Ga1vnlJ6moq+8+4i20GEjnj24BiRrdtVs3DXPQAWw1zYykl1UAGiYPWx6GRO+04ePi1R5ZIPg6p07l5kw3fSm048O35iZ4gCyB4Xgp+w00mSZEm2XwlYcHKdjL+qrSGIKSfFkztRHDARwV++muYzBXfR1W9DrqCAD6Hh2UsXFurIKQ+5DSpBDpzAiwH8N7aXmOWvDZFNO5CjwKGnLp347UIWKlz4wrtVT9J8RZJ8TH/FF+iuiS7RxhXk9sfByFHRRuRTdMbj+mo6JCzfiw39pgi/MwZ+cF3aWAW556EeSPuLgmouyX8gPf8vGapuUJKhxh+irweYaZzquk1vAc/v47VBJWuxxa9vdbFkFUyo5LbiKnEm4GMcAk8YMdRF4UnaXPysIJUwytb2S6hrr4TRTJozqDv/T9hkfq2OgBkdCF8KkvWQ9CSsvZoaX+wC5/3OucT5xhyLVe0i4Ix+ushA5AlsPHAZoeih8YxNVFxWm5aJWHYc4vxABCEzISTPZyD1XwjeO5faaVUuGU7wLbiRNOsLy1Gvz4uqAB+ZlTsog/Uv81c7395zeX6w6kzrEyG0Tc+M=
before_install:
- pip install codecov tox>=1.8 virtualenv==13.1.2
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then export PYVER=py26; fi
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.0' ]]; then export PYVER=py30; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.1' ]]; then export PYVER=py31; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then export PYVER=py32; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export PYVER=py33; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi
script: COMMAND='coverage run' tox -e$PYVER
after_success:
- codecov
deploy:
  provider: pypi
  user: nekmo
  password:
    secure: GOC9TIfJEc+hC9uyT9K8ir1zua19Dg0txGdhhJF72TFUpNpvtS6i1HseF6qj+KxOkedD6T7Q49xllxGgdF8uKK1YDoWjt2Fqxvtm56DO844QbSunTMEQUAC2kiwOZyG2pBVsiJ/IlanWAH9lx5PsRGKtcdDZa2MpLm/w2OUwiYoMiwzGcxa/kktZjQpRs13NDOy8NJAozmcUZZPrXKV67egfPJYVcqDd7RE+M179o16JGCumUUYPVo0qY4daKSsJBLcxZqZEX7jth9VqbWzMZfLkY+CGTfdcgycjsi5G6zAIWoiP9OaoF0xPtPjr/FmzXmjlxkoCWvG+K7ZlNyGjOu97NOKKn0ilXN0nXDCTx1ZM31u07p+MlZ86FiZUOkDZVI0hT5xtUQHsIzfGrIHjpXMs3xPyYuvVpS1hiyOc+RqO0N25Iuv6cGhG0PK+Wj3eFX/MUQw9d4gY04FOg7V/Wk5cor//doFgO/y4C2OwFmVYfDjk3yxnoORJjtAB0maoy07xaAt/uAV738olji64lX6R0lLM2W6zzb+CadrsLsc2cE25SCQe1OfyW/wVM9vXDIzMWC7toPtGvU97QtPXEbhChgb78+lOeDVUXCPlVKPVrswh2CSr6nQ5DjnQr/kRkBH7r63rBIIQrPyjtGsaDBoYRI7EpXA9yyucKiux6kM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Nekmo/python-akismet
